<!--
For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

@copyright #legal.notice#
@version #Id#
@built #buildtime#
-->
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <div><?php 
            echo $partial;
        ?></div>
    </body>
</html>
