<?php
namespace Core;
require_once dirname(__FILE__) . '/../../core/FrontController.php';

/**
 * Test class for FrontController.
 * Generated by PHPUnit on 2012-05-27 at 12:50:31.
 */
class FrontControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FrontController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = FrontController::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testInstance().
     */
    public function testInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testInitialize().
     */
    public function testInitialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testRouteController().
     */
    public function testRouteController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
