<?php

namespace Core;

require_once dirname(__FILE__) . '/../../core/Router.php';

/**
 * Test class for Router.
 * Generated by PHPUnit on 2012-05-27 at 21:28:03.
 */
class RouterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Router
     */
    protected $object;
    private $controller = 'Index';
    private $action     = 'index';
    private $params     = array('name','Dario');

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $url = "/" . $this->controller . "/" . $this->action . "/" . join("/",$this->params);
        $this->assertEquals($url, '/Index/index/name/Dario');
        $this->object = new Router($url);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testRouteController() {
        $test = array('name' => $this->params[1]);
        $this->assertEquals($test, $this->object->routeController());
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testGetController() {
        $this->assertEquals($this->controller, $this->object->getController());
    }
    public function testGetFullQualifiedController() {
        $test = 'Application\\' . $this->controller;
        $this->assertEquals($test, $this->object->getFullQualifiedController());
    }
    /**
     * @covers {className}::{origMethodName}
     */
    public function testSetController() {
        $this->assertFalse($this->object->setController('3333dsd00:::\\/'));
        $this->assertEquals($this->controller, $this->object->setController($this->controller));
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testGetAction() {
        $this->assertEquals($this->action, $this->object->getAction());
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testSetAction() {
        $this->assertFalse($this->object->setAction('__construct'));
        $this->assertEquals($this->action, $this->object->setAction($this->action));
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testGetParams() {
        $this->assertEquals(Array('name' => 'Dario'), $this->object->getParams());
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testSetParams() {
        $test = array('rape', 'is', 'fun');
        $this->assertEquals($test, $this->object->setParams($test));
        $this->assertEquals($this->params, $this->object->setParams($this->params));
    }

    /**
     * @covers {className}::{origMethodName}
     */
    public function testGetClassesPath() {
       $test = '/home/asphyxia/projects/phpframework/core/../application/controllers/';
       $this->assertEquals($test, $this->object->getClassesPath());
    }
    /**
     * @covers {className}::{origMethodName}
     */
    public function testSetClassesPath() {
        $test = 'C:\Windows\XP/var/tmp/bin:/usr/bin/perl -w';
        $this->assertFalse($this->object->setClassesPath($test));
        
        $test = '../un/exis/ten/t/pat/hcla/ss/';
        $this->assertFalse($this->object->setClassesPath($test));
        
        $path = '../application/controllers/';
        $test = '/home/asphyxia/projects/phpframework/core/';
        $this->assertEquals($test . $path, $this->object->setClassesPath($path));
    }

}

?>
