include:
    constant.yml

system:
    controllers_directory : /../application/controllers/
    render :
        path  : /../core/Render.php
        name  : Core\Render
    
db>system:
    host      : localhost
    user      : root
    password  : toor
    database  : ajaxchat

render:
    config:
        layouts: ../layout/
        themes : ../themes/
        pages  : ../pages/
        extension: .phtml
    pages:
        hello:
        home:
        about:

# je veux dormir, dormir plutot que vivre      